### ISSUE TITLE
`Backpex.Field.URL`: add option to configure anchor text

### ISSUE THREAD

**Issue by pehbehbeh** [naymspace/backpex#321]
You should be able to determine the text of the anchor that is displayed on `index`/`show` view via a configuration value. Currently, the URL is used as the anchor text.

### Todos

- [ ] Add new field option to `config_schema` (include documentation)
  - [ ] Allow a function to be passed as an option that at least receives the assigns
- [ ] Determine label in `render_value`, show URL by default (if no configuration is provided)
